### PR TITLE
added retake button

### PR DESCRIPTION
**Pull request by zommerberg**
Added a retake button that is visible only for 'ROLE_SURVEY_TAKER' and  'ROLE_SURVEY_USER_ADMIN'

### CODE REVIEW

**Comment by loorely** [comment]
@zommerberg Hey! there is a mistake in the role names, users that can do the retake are: 
ROLE_SURVEY_USER and ROLE_SURVEY_USER_ADMIN

**Comment by zommerberg** [comment]
@loorely  this is how it was described in the lab. I have pushed a quick fix for it

**Comment by loorely** [comment]
@zommerberg using a ROLE_SURVEY_USER role user I was not able to see the button: 

image

**Comment by zommerberg** [comment]
it is fixed now

**Pull request merged**
